version: '3.8'

services:
  # Servicio para la aplicación del bot
  bot:
    build: .
    container_name: telegram_bot_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  # Servicio para la base de datos PostgreSQL
  db:
    # Es mejor práctica usar una versión específica en lugar de 'latest'
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    # Solo usamos env_file para cargar las credenciales
    env_file:
      - .env
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  # Servicio para Redis (la cola de tareas)
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always

  # Servicio para el Worker de Celery
  worker:
    build: .
    container_name: celery_worker
    restart: always
    command: celery -A src.tasks worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - PYTHONUNBUFFERED=1

# Define el volumen que usará el servicio 'db'
volumes:
  postgresdb_data: