version: '3.8'

services:
  # Servicio para la aplicación del bot
  # bot:
  #   build: .
  #   container_name: telegram_bot_app
  #   restart: always
  #   env_file:
  #     - .env
  #   # El bot depende de que la base de datos esté lista
  #   depends_on:
  #     - db

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    restart: always
    # Carga las credenciales desde el .env para inicializar la DB
    env_file:
      - .env
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# Define el volumen que usará el servicio 'db' para la persistencia
volumes:
  postgresdb_data: # <-- Sintaxis corregida (sin la coma al final)